[project]
name = "work"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mlflow>=1.27.0",
    "numpy>=2.4.2",
    "plotnine>=0.15.3",
    "polars>=1.38.1",
    "pyarrow>=23.0.0",
]
